### ISSUE TITLE
AsmUtilX64.cs Question

### ISSUE THREAD

**Issue by superolg999** [marlkiller/PluginHelper#1]
请问AsmUtilX64.cs档案里的问题,如果是Mov RCX QWORD Ptr RCX Add或是Mov RCX QWORD Ptr RAX Add的机器码或汇编内容是?
跟Mov_ECX_DWORD_Ptr_ECX_Add或Mov_ECX_DWORD_Ptr_EAX_Add一样吗?

**Comment by marlkiller** [comment]
汇编 x64下 操作低位的话 实际上机器码 与 x86下一样
比如 mov rax,0x1  == mov eax,0x1,
rax 如果 大于 Int32.Max , 操作高位则就不一样了,
